spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/oj?serverTimezone=Asia/Shanghai
    username: root
#    password: 119pld
    password: 119pldRoot*
#  web:
#    resources:
#      static-locations: classpath:/res/**
  mvc:
    static-path-pattern: /res/**
  resources:
    static-locations: [classpath:/static/]

sms:
  accessKeyId: yourKey
  secret: you
  signName: oj网站登录验证
  templateCode: you
  regionId: cn-hangzhou

path:
  filePath: /Oj/file/
#  filePath: D:\testOj\
  shellPathCode: /root/shells/complie.sh
  filePathCompiled: /Oj/compile
  shellPathRun: /root/shells/run.sh
